config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :tags
  resources :items
  get 'welcome/index'

  get 'welcome/about'

  get 'about_us' => 'welcome#about'
  get 'welcome' => 'welcome#index'
  get 'my_closet' => 'items#index'
  post 'add_to_outfit' => 'outfit#add_to_outfit'
  get 'view_outfit' => 'outfit#view_outfit'
  get 'get_dressed' => 'outfit#get_dressed'
  get 'past_outfits' => 'outfit#past_outfits'
  get 'show_outfit' => 'outfit#show'

  delete 'remove' => 'outfit#remove', as: 'remove_line_item'



  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  mount_uploader :image, AvatarUploader
  belongs_to :user

  has_and_belongs_to_many :tags

  TYPES = [:shirt, :pants, :shorts, :skirt, :dress, :outerwear, :shoes, :accessory]
  COLORS = [:black, :white, :grey, :brown, :beige, :purple, :blue, :green, :yellow, :orange, :red, :pink, :multi]

  paginates_per 20
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :item
  belongs_to :order, optional: true
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :line_items
  belongs_to :user, optional: true

  serialize :order_items, Hash
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_and_belongs_to_many :items
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :items
  has_many :tags
  has_many :orders
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

  helper_method :current_order

  def current_order
    if !session[:order_id].nil?
      Order.find(session[:order_id])
    else
      Order.new
    end
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index

    @q = current_user.items.ransack(params[:q])
    @items = @q.result(distinct: true).page(params[:page])

  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:category, :color, :image, :user_id, tag_ids:[])
    end
end

app/controllers/outfit_controller.rb
class OutfitController < ApplicationController
  def show
    @order = Order.find(params[:id])
  end

  def add_to_outfit
    @order = current_order

    line_item = @order.line_items.new(item_id: params[:item_id])
    @order.save
    session[:order_id] = @order.id

    redirect_back(fallback_location: root_path)
  end

  def view_outfit
    @line_items = current_order.line_items
  end

  def get_dressed
    line_items = current_order.line_items

    if line_items.length != 0
      current_order.update(user_id: current_user.id)

      @order = current_order

      @order.save

      session[:order_id] = nil
    end
  end

  def remove
    @order = current_order
    line_item = LineItem.find(params[:line_item_id]).destroy

    session[:order_id] = @order.id

    redirect_to view_outfit_path
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: [:show, :edit, :update, :destroy]

  # GET /tags
  # GET /tags.json
  def index
    @tags = current_user.tags.all
  end

  # GET /tags/1
  # GET /tags/1.json
  def show
  end

  # GET /tags/new
  def new
    @tag = Tag.new
  end

  # GET /tags/1/edit
  def edit
  end

  # POST /tags
  # POST /tags.json
  def create
    @tag = Tag.new(tag_params)

    respond_to do |format|
      if @tag.save
        format.html { redirect_to @tag, notice: 'Tag was successfully created.' }
        format.json { render :show, status: :created, location: @tag }
      else
        format.html { render :new }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tags/1
  # PATCH/PUT /tags/1.json
  def update
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to @tag, notice: 'Tag was successfully updated.' }
        format.json { render :show, status: :ok, location: @tag }
      else
        format.html { render :edit }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1
  # DELETE /tags/1.json
  def destroy
    @tag.destroy
    respond_to do |format|
      format.html { redirect_to tags_url, notice: 'Tag was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = Tag.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tag_params
      params.require(:tag).permit(:name, :user_id)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :authenticate_user!, :except => [:index, :about]

  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/outfit_helper.rb
module OutfitHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/items/_form.html.erb
<%= form_with(model: item, local: true) do |form| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <strong>Upload Clothing Image: </strong>
    <%= form.file_field :image, class:"form-control-file" %>
  </div>

  <div class="form-group">
    <%= form.select :category, Item::TYPES, {include_blank: "Please select a category" } %>
  </div>

  <div class="form-group">
    <%= form.select :color, Item::COLORS, {include_blank: "Please select a color" } %>
  </div>

  <div class="field">
    <%= form.label "Item Tags" %><br />
    <%= form.collection_check_boxes :tag_ids, current_user.tags.all, :id, :name do |b| %>
      <div class="collection-check-box">
        <%= b.check_box %>
        <%= b.label %>
      </div>
    <% end %>
  </div>

  <div class="form-group">
    <%= form.hidden_field :user_id, value: current_user.id %>
  </div>

<div class="container col-xs-12">
  <div class="actions">
    <%= form.submit 'Add Clothing', class:"btn btn-primary" %>
  </div>
</div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing Item</h1>
<div>
<%= render 'form', item: @item %>
</div>
<br />
<div>
  <p>
<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %> |
<%= link_to 'Remove Item', @item, method: :delete, data: { confirm: 'Are you sure?' } %>
</p>
</div>

app/views/items/index.html.erb
<p id="notice"><%= notice %></p>

<div class="jumbotron" id="smalltron">
<h1 class="text-right"><em>My Closet</em></h1>
</div>


<div>
    <%= search_form_for @q do |f| %>
    <div class="form-group col-xs-3">
<%= f.label :name_cont, "Category: " %>
  <%= f.select :category_cont, Item::TYPES, include_blank: true, class:"form-control" %>
</div>
<div class="form-group col-xs-3">
  <%= f.label :name_cont, "Color: " %>
  <%= f.select :color_cont, Item::COLORS, include_blank: true, class:"form-control" %>
</div>
<div class="form-group col-xs-8">
    <%= f.label "Tags:" %><br/>
<%= f.collection_check_boxes :tags_id_in, current_user.tags.all, :id, :name do |b| %>
  <div class="collection-check-box checkbox-inline">
    <%= b.check_box %>
    <%= b.label %>
  </div>
<% end %>
</div>
<div class="form-group col-xs-12">
  <%= f.submit 'Search My Closet', class:"btn btn-primary" %>
</div>
<% end %>
  </div>


  <div class="media col-xs-12 col-lg-12" id="mediaitem">
    <% @items.each do |item| %>
<div class="thumbnail col-xs-5 col-lg-5">
      <div class="media-left">
        <% if item.image.nil? == false %>
        <p class="media-object"><%= image_tag item.image, height:"200px" %></p>
        <% end %>
      </div>
      <div class="media-body">
        <p><% if item.category.nil? == false %>
          <%= item.category.capitalize %>
          <% end %></p>
          <p><% if item.color.nil? == false %>
            <%= item.color.capitalize %>
            <% end %></p>
            <p><%= item.tags.map(&:name).sort.join(", ") %></p>
        <p><%= link_to 'Show', item %> |
          <%= link_to 'Edit', edit_item_path(item) %>
          <p>
            <a href="#" data-toggle="modal" data-target="#myModal_<%= item.id %>">
              <span class="glyphicon glyphicon-plus"></span> Quick View
            </a>
          </p>

          <div class="modal fade " id="myModal_<%= item.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
            <div class="modal-dialog" role="document">
              <div class="modal-content">
                <div class="modal-body">
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
                </div>
                <div class="modal-body text-center">
                  <% if item.image.url.nil? == false %>
                    <p><%= image_tag item.image.url, class: "center-block", height: "300px" %></p>
                  <% end %>
                  <h3><%= link_to item.category.capitalize, item %></h3>
                  <p><%= item.color.capitalize %></p>
                  <p><%= item.tags.map(&:name).sort.join(", ") %></p>
                </div>
                <div class="modal-footer">
                  <p>
                    <%= form_tag add_to_outfit_path do %>
                    <%= hidden_field_tag :item_id, item.id %>
                    <%= submit_tag "Add to Outfit", class: "btn btn-primary center-block" %>
                    <% end %>
                  </p>
                </div>
              </div>
            </div>
          </div>

      </div>
    </div>
    <% end %>
  </div>


<nav aria-label="Page navigation" class="container col-xs-12 col-sm-12 col-md-12 col-lg-12">
  <div class="pagination">
<%= paginate @items %>
</div>
</nav>

app/views/items/new.html.erb
<div class="jumbotron" id="smalltron">
<h1 class="text-right"><em>New Item</em></h1>
</div>

<div class="container col-xs-6">
<%= render 'form', item: @item %>

</div>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <%= image_tag @item.image, width:"200px"%>
</p>

<p>
  <strong>Category:</strong>
  <% if @item.category.nil? == false %>
  <%= @item.category.capitalize %>
  <% end %>
</p>

<p>
  <strong>Color:</strong>
  <% if @item.color.nil? == false %>
  <%= @item.color.capitalize %>
  <% end %>
</p>

<p>
  <strong>Tags:</strong>
  <% @item.tags.each do |tag| %>
  <%= tag.name %>
  <% end %>
</p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'My Closet', items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    
    <title>Dressed</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href='https://fonts.googleapis.com/css?family=Jaldi' rel='stylesheet'>
    <link href='https://fonts.googleapis.com/css?family=Syncopate' rel='stylesheet'>
  </head>

  <body>
    <% if user_signed_in? %>
    <nav class="navbar navbar-default">
      <div class="container">
        <ul class="nav navbar-nav">
          <li class="navbar-brand" id="brand">
            <%= link_to image_tag("icon.png", height:"25px", id:"brand"), root_path %>
          </li>
          <li>
            <%= link_to 'My Closet', items_path(name: current_user.name) %>
          </li>
          <li>
            <%= link_to 'New Item', new_item_path %>
          </li>
          <li>
            <%= link_to 'New Item Tag', new_tag_path %>
          </li>
        </ul>

          <ul class="nav navbar-nav navbar-right">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">

                Welcome, <%= current_user.name %>!
                <span class="glyphicon glyphicon-chevron-down"></span>
              </a>
              <ul class="dropdown-menu">
                <li>
                    <div class="row">
                      <div class="col-lg-5">
                        <p class="text-center">

                          <strong><%= current_user.name %></strong>
                        </p>

                      </div>
                    </div>
                    <li>
                        <p class="text-center small"><%= current_user.email %></p>
                      </li>
                      <li class="divider"></li>
                      <li><p class="text-center"><%= link_to "View Outfit", view_outfit_path %></p></li>
                      <li><p class="text-center"><%= link_to "Past Outfits", past_outfits_path %></p></li>
                      <li class="divider"></li>
                      <li>
                        <p class="text-center">
                          <%= link_to "Edit Profile", edit_user_registration_path %>
                        </p>
                      </li>
                </li>
                <li>
                  <div class="navbar-login navbar-login-session">
                    <div class="row">
                      <div class="col-lg-8">
                        <p class="text-center">
                          <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
                        </p>
                      </div>
                    </div>
                  </div>
                </li>
              </ul>
            </li>
          </ul>
        </div>
        </nav>
        <% else %>
        <nav class="navbar navbar-default navbar-static-top">
          <div class="container">
            <ul class="nav navbar-nav">
              <li>
                <%= link_to 'Home', root_path %>
              </li>
              <li>
                <%= link_to 'About Us', about_us_path %>
              </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <li>
                <%= link_to 'Log In', new_user_session_path %>
              </li>
              <li>
                <%= link_to 'Sign Up', new_user_registration_path %>
              </li>
            </ul>
          </div>
        </nav>
        <% end %>
<div id="backcolor">
  <div class="container">
    <%= yield %>
  </div>
</div>

  </body>
</html>

app/views/outfit/add_to_outfit.html.erb
<h1>Outfit#add_to_outfit</h1>
<p>Find me in app/views/outfit/add_to_outfit.html.erb</p>

app/views/outfit/get_dressed.html.erb
<div class="jumbotron" id="smalltron">
<h1 class="text-right"><em>My Outfit</em></h1>
</div>

<h2 class="text-center">Today's Outfit</h2>


<% @order.line_items.each do |line_item| %>
  <div class="thumbnail col-xs-3"><%= image_tag line_item.item.image, height:"200px"%></div>
<% end %>

app/views/outfit/past_outfits.html.erb
<div class="jumbotron" id="smalltron">
<h1 class="text-right"><em>Past Outfits</em></h1>
</div>

<table class="table">
  <thead>
    <tr>
      <th>Worn on:</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
<% current_user.orders.reverse_each do |order| %>
<tr>
  <td><%= order.created_at.strftime("%A, %b %d, %Y") %></td>
  <td><%= link_to 'Show', show_outfit_path(id: order.id) %></td>
</tr>
<% end %>
</tbody>
</table>

app/views/outfit/show.html.erb
<div class="jumbotron" id="smalltron">
<h1 class="text-right"><em>Past Outfit</em></h1>
</div>

<div class="col-xs-12">
<h4>Worn on <%= @order.created_at.strftime("%A, %b %d, %Y") %>:</h4>
</div>

<div>
<% @order.line_items.each do |line_item| %>
  <p class="thumbnail col-xs-3"><%= image_tag line_item.item.image, height:"200px"%></p>
<% end %>
</div>

<div class="col-xs-12">
  <%= link_to "Back", past_outfits_path %>
</div>

app/views/outfit/view_outfit.html.erb
<div class="jumbotron" id="smalltron">
<h1 class="text-right"><em>My Outfit</em></h1>
</div>

<div>
  <% @line_items.each do |line_item| %>
  <div class="thumbnail">
        <div class="media-left">
          <% if line_item.item.image.nil? == false %>
          <p class="media-object"><%= image_tag line_item.item.image, height:"200px" %></p>
          <% end %>
        </div>
        <div class="media-body">
          <p><% if line_item.item.category.nil? == false %>
            <%= line_item.item.category.capitalize %>
            <% end %></p>
            <p><% if line_item.item.color.nil? == false %>
              <%= line_item.item.color.capitalize %>
              <% end %></p>
              <p><%= line_item.item.tags.map(&:name).sort.join(", ") %></p>
          <p><%= link_to 'Show', line_item.item %> |
            <%= link_to 'Remove', remove_line_item_path(line_item_id: line_item.id), method: :delete %> </p>
          </div>
        </div>
  <% end %>
</div>

<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
  <%= link_to "Get Dressed", get_dressed_path, class: "btn btn-primary" %>
</div>

app/views/tags/_form.html.erb
<%= form_with(model: tag, local: true) do |form| %>
  <% if tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tag.errors.count, "error") %> prohibited this tag from being saved:</h2>

      <ul>
      <% tag.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, id: :tag_name, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.hidden_field :user_id, value: current_user.id %>
  </div>

  <div class="actions">
    <%= form.submit 'Add Tag', class:"btn btn-primary" %>
  </div>
<% end %>

app/views/tags/edit.html.erb
<h1>Editing Tag</h1>

<%= render 'form', tag: @tag %>

<%= link_to 'Show', @tag %> |
<%= link_to 'Back', tags_path %>

app/views/tags/index.html.erb
<p id="notice"><%= notice %></p>

<div class="jumbotron" id="smalltron">
<h1 class="text-right"><em>Item Tags</em></h1>
</div>

<%= link_to 'New Tag', new_tag_path, class:"btn btn-primary" %>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tags.each do |tag| %>
      <tr>
        <td><%= tag.name %></td>
        <td><%= link_to 'Edit', edit_tag_path(tag) %></td>
        <td><%= link_to 'Destroy', tag, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/tags/new.html.erb
<div class="jumbotron" id="smalltron">
<h1 class="text-right"><em>New Item Tag</em></h1>
</div>

<p>Add tag descriptions so you can better organize your closet.</p>
<p><em>Example: Cold Weather, Work Appropriate, etc.</em></p>

<%= render 'form', tag: @tag %>

<br />
<%= link_to 'Show All', tags_path %>

app/views/tags/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @tag.name %>
</p>

<%= link_to 'Edit', edit_tag_path(@tag) %> |
<%= link_to 'Back', tags_path %>

app/views/welcome/about.html.erb
<body id="background">
  <div id="abouttron" class="col-xs-8 col-xs-offset-2">
    <div class="text-center">
      <h1>About Dressed</h1>
      <p>
        Inspired by the iconic scene from the movie Clueless, our website allows you to catalog your wardrobe and search through it using various criteria in order to find the perfect outfit! Stop forgetting about the clothes in the back of your closet and try different looks without the mess. Let Dressed be your new stylist and help you live a totally normal life!
      </p>
      <div class="embed-responsive embed-responsive-16by9" id="video">
        <iframe width="560" height="315" src="https://www.youtube.com/embed/XNDubWJU0aU" frameborder="0" allowfullscreen></iframe>
      </div>
      <h3>How it Works</h3>
      <p>
        Build your closet by taking pictures of your clothes and adding them in New Item. Use New Item Tag to create better ways to describe your clothes. Use tags to specify anything from season to length to rise to occasion. The possibilities are endless and customizable so you can decide how you get Dressed.
      </p>
    </div>

  </div>
</body>

app/views/welcome/index.html.erb
<body id="background">
<div id="hometron" class="jumbotron text-center">
  <h1><em>Dressed</em></h1>
  <br />
  <p>Use technology to answer the day's most difficult question:</p>
  <p>What to Wear?</p>
  <br />
  <p><%= link_to 'Log In', new_user_session_path, {class: "btn btn-default"} %>
  <%= link_to 'Sign Up', new_user_registration_path, {class: "btn btn-default"} %></p>
  <br />
  <p><%= link_to 'About Dressed', about_us_path %></p>
</div>
</body>
<div class="container-fluid navbar-fixed-bottom">
  <h5><small>@ EJ Technologies |
    <%= link_to 'Home', root_path %> |
    <%= link_to 'About Us', about_us_path %></small></h5>
  </div>